### ISSUE TITLE
Span?

### ISSUE THREAD

**Issue by vasilisvg** [VincentKempers/cssttr#1]
https://github.com/VincentKempers/cssttr/blob/a0ac50821cb54646be4ce1f01ca0c577b44fc80a/styles.css#L55

Dit kan ook/juist zonder extra `span`!

**Comment by VincentKempers** [comment]
thanks for the feedback !
[fixed](https://github.com/VincentKempers/cssttr/commit/da93aa724424c5c45369e18167e904cb7f91a66e)
